version: '3.8'
networks:
  coolify:
    driver: bridge
services:
  coolify:
    container_name: coolify
    image: coollabsio/coolify
    restart: unless-stopped
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    networks:
      - coolify
    volumes:
      - ".docker-volumes/coolify/db:/app/db"
      - ".docker-volumes/coolify/ssl:/app/ssl"
      - "~/.cert:/etc/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock"
    env_file: [.env]
    environment:
      - COOLIFY_IS_ON=docker
      - COOLIFY_WHITE_LABELED=false
      - COOLIFY_AUTO_UPDATE=false
      - COOLIFY_DATABASE_URL=file:/app/db/dev.db
  coolify-redis:
    container_name: coolify-redis
    image: bitnami/redis:6.2
    restart: unless-stopped
    networks:
      - coolify
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
